package: yrewrite_url_redirect
version: '1.2.0'
author: 'Alexander Walther'
supportpage: www.github.com/alexplusde/yrewrite_url_redirect
load: late

requires:
    php:
        version: '^8.1'
    redaxo: ^5.17
    packages:
        yrewrite: ^2.10
    
conflicts:
    packages:
        yrewrite_scheme: '*'

pages:
    yrewrite/forward_options:
        title: 'translate:yrewrite_url_redirect'

default_config:
    force_trailing_slash: 1
    force_forward: 1
