package: yrewrite_url_redirect
version: '1.1'
author: 'Alexander Walther'
supportpage: www.github.com/alexplusde/yrewrite_url_redirect
load: late

requires:
    php:
        version: '^7.3'
    redaxo: ^5.10
    packages:
        yrewrite: ^2.6
    
conflicts:
    packages:
        yrewrite_scheme: '*'

pages:
    yrewrite/forward_options:
        title: 'translate:yrewrite_url_redirect'

default_config:
    force_trailing_slash: 1
    force_forward: 1
